# **Basic Syntax in R Programming**

In [ ]:
%load_ext rpy2.ipython

## 1. Variable

In [ ]:
%%R
# 1. Variable in r
x <- 10
print(x)

y = 20
print(y)

z <- TRUE
print(z)

[1] 10
[1] 20
[1] TRUE


In [ ]:
var.1 <- 5
var.name <- 10
# _var <- 15 # invalid (start wiht Underscore)
# 2var = 30 #invalid(Starts with a number)

#case Sensitivity
Var <- 100 #Output : 100
var <- 200 # Output : 200

print(Var)
print(var)

[1] 100
[1] 200


In [ ]:
#  Variable Assignment Methods :
a <- 15  # Using <-
b = 10 # Using =
30 -> c # using ->
assign("c", 25)

print(a)
print(b)
print(c)

[1] 15
[1] 10
[1] 25


In [ ]:
#  Dynamic Typing R
x <- 10 # x is numeric
x <- "R Programming" # Now x is character
print(x) # Output: "R Programming"

[1] "R Programming"


## 2. Comments in R

In [ ]:
# This is a single-line comment
# Multi-line comments can be written as:
# Line 1
# Line 2
# Line 3
# Alternatively, use if(FALSE) to block comment
x=10
if(FALSE){
# This is a multi-line comment.
# It won't be executed.
x <- 5 + 10
}
print(x)
# Example with code
x <- 10 # Assigning 10 to x
y <- x * 2 # Doubling x and storing in y
print(y) # Output: 20

[1] 10
[1] 20


## 3. Keywors in R


In [ ]:
x = 11
if(x == 10 ){
  print("print x = 10")
}else{
  print("print x != 10")
}

for(i in 1:5){
  print(i)
}

c = 1
while(c <= 3){
  print(paste("Count is", c))
  c = c + 1
}

n = 5
s <- function(n){
  return (n ** n)
}
print(s(3))

for (i in 1:10) {
if (i == 6) {
break
}
print(i)
}

for (i in 1:5) {
if (i == 3) {
next
}
print(i)
}

# if <- 10 # Error: unexpected assignment in "if <-"
# TRUE <- 5 # Error: invalid assignment to 'TRUE'
# function <- "test" # Error: invalid assignment to 'function'

[1] "print x != 10"
[1] 1
[1] 2
[1] 3
[1] 4
[1] 5
[1] "Count is 1"
[1] "Count is 2"
[1] "Count is 3"
[1] 27
[1] 1
[1] 2
[1] 3
[1] 4
[1] 5
[1] 1
[1] 2
[1] 4
[1] 5


# R Operators and R Data Types

In [ ]:
a <- 10
b <- 3
print(a + b) # 13
print(a - b) # 7
print(a * b) # 30
print(a / b) # 3.333//floating point division
print(a ^ b) # 1000
print(a %% b) # 1 (remainder of integer division)
print(a %/% b) # 3 (quotient of integer division)

[1] 13
[1] 7
[1] 30
[1] 3.333333
[1] 1000
[1] 1
[1] 3


In [ ]:
x <- 10
y <- 5
print(x == y) # FALSE
print(x != y) # TRUE
print(x != y) # TRUE
print(x > y) # TRUE
print(x < y) # FALSE
print(x >= y) # TRUE
print(x <= y) # FALSE

[1] FALSE
[1] TRUE
[1] TRUE
[1] TRUE
[1] FALSE
[1] TRUE
[1] FALSE


In [ ]:
a <- TRUE
b <- FALSE
print(a & b) # FALSE
print(a | b) # TRUE
print(!a) # FALSE
print(a && b) # FALSE (stops if first condition is FALSE)
print(a || b) # TRUE (stops if first condition is TRUE)

[1] FALSE
[1] TRUE
[1] FALSE
[1] FALSE
[1] TRUE


In [ ]:
# Sequence operator
seq <- 1:5
print(seq) # 1 2 3 4 5
# %in% operator
print(3 %in% c(1, 2, 3)) # TRUE
# Matrix multiplication
mat1 <- matrix(1:4, nrow=2)
mat2 <- matrix(1:25,nrow=5)
# print(mat1 %*% mat2)
# Output:
# [,1] [,2]
# [1,] 19 22
# [2,] 43 50

m <- matrix(20:1, nrow = 4 , ncol = 5)
print(m %*% mat2)

#      [,1] [,2] [,3] [,4] [,5]
# [1,]  140  440  740 1040 1340
# [2,]  125  400  675  950 1225
# [3,]  110  360  610  860 1110
# [4,]   95  320  545  770  995

print(m[3][3])

[1] 1 2 3 4 5
[1] TRUE
     [,1] [,2] [,3] [,4] [,5]
[1,]  140  440  740 1040 1340
[2,]  125  400  675  950 1225
[3,]  110  360  610  860 1110
[4,]   95  320  545  770  995
[1] NA


In [ ]:
num <- 10.5 # Numeric
int <- 5L # Integer
char <- "Hello" # Character
bool <- TRUE # Logical
comp <- 3 + 2i # Complex
print(class(num)) # "numeric"
print(class(int)) # "integer"
print(class(char)) # "character"
print(class(bool)) # "logical"
print(class(comp)) # "complex"

[1] "numeric"
[1] "integer"
[1] "character"
[1] "logical"
[1] "complex"
